if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

hsetroot -center $XDG_CONFIG_HOME/wall
xgamma -bgamma 0.65
sudo xbacklight 20
xset dpms 0 0 240
setxkbmap "us,ru" ",winkeys" "grp:toggle,altwin:swap_lalt_lwin,caps:swapescape"
xmodmap $XDG_CONFIG_HOME/X11/modmap
xsetroot -cursor_name left_ptr
xinput disable 'SynPS/2 Synaptics TouchPad'

redshift &
pokoy -r &
sxhkd &
xbanish &

exec bspwm
#exec i3
