if [ -d /etc/X11/xinit/xinitrc.d ] ; then
 for f in /etc/X11/xinit/xinitrc.d/?*.sh ; do
  [ -x "$f" ] && . "$f"
 done
 unset f
fi

hsetroot -fill $XDG_CONFIG_HOME/X11/wall
xgamma -bgamma 0.65
sudo xbacklight 20
xset -b dpms 0 0 240
$XDG_CONFIG_HOME/X11/keys
xsetroot -cursor_name left_ptr
xinput disable 'SynPS/2 Synaptics TouchPad'

physlock -sm &

blueman-applet &
redshift &
pokoy -r &
sxhkd &
xbanish &

exec bspwm
