#! /bin/sh

bars &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           3
bspc config top_padding          18

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# Border colors
bspc config focused_border_color '#fbf1c7'

# Rules for apps
bspc rule -a Zathura state=tiled
bspc rule -a Blueman-manager center=on rectangle=800x600+0+0
bspc rule -a discord rectangle=900x600+0+0 center=on
bspc rule -a Telegram center=on rectangle=900x600+0+0
