#! /bin/sh

bars &

bspc monitor -d 1 2 3 4 5 6

bspc config border_width         2
bspc config window_gap           3

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config single_monocle       true

# Border colors
#bspc config focused_border_color '#dbae93'
bspc config focused_border_color '#fbf1c7'

# Rules for apps
bspc rule -a Zathura state=tiled
