#!/bin/zsh

# Gives a dmenu prompt to search DuckDuckGo.
# Without input, will open DuckDuckGo.com.
# URLs will be directly handed to the browser.
# Anything else, it search it.
browser=qutebrowser

pgrep -x dmenu && exit

choice=$(echo " " | rofi -dmenu -i -p "Search DuckDuckGo" -lines 3 -width 40) || exit 1

if [ "$choice" = " "  ]; then
    $browser "https://duckduckgo.com"
else
    # Detect if url
    if [[ "$choice" =~ ^(http:\/\/|https:\/\/)?[a-zA-Z0-9]+\.[a-zA-Z]+(/)?.*$ ]]; then
        $browser "$choice"
    else
        $browser "https://duckduckgo.com/?q=$choice&t=ffab&atb=v1-1"
    fi
fi
