#!/bin/sh
dir="$HOME/diskg/watch"
watching=""
series=$(ls $dir/$watching | grep .mkv)
choice=$(echo -e "$series" | rofi -width 40 -sep "\n" -dmenu)
if [ "$choice" ]; then
mpv --sub-auto=fuzzy "$dir/$watching/$choice"
fi
