#!/bin/sh
choice=$(echo -n "suspend\nlock\npoweroff\nreboot" | rofi -dmenu) || exit 1
if [ $choice = "suspend" ]; then
  sudo zzz
elif [ $choice = "lock" ]; then
  xset dpms force off && slock
elif [ $choice = "poweroff" ]; then
  sudo poweroff
elif [ $choice = "reboot" ]; then
  sudo reboot
fi
